# 🏆 TFT Leaderboard Crawler - VN2 Server

In [16]:
# ========================================
# CELL 1: CONFIG
# ========================================

import os
import requests
import time
import json
import pandas as pd
from datetime import datetime
from dotenv import load_dotenv

# load Riot API Key
load_dotenv()
RIOT_API_KEY = os.getenv("RIOT_API_KEY")

PLATFORM = "vn2"
REGION_ACCOUNT = "asia"
REGION_MATCH = "sea"

TOP_N = 70
MATCH_COUNT_PER_PLAYER = 200

print("✅ Config loaded!")

✅ Config loaded!

In [17]:
# ========================================
# CELL 2: API FUNCTIONS
# ========================================

def make_api_request(url, params=None):
    headers = {"X-Riot-Token": RIOT_API_KEY}
    try:
        response = requests.get(url, headers=headers, params=params)
        if response.status_code == 200:
            return response.json()
        elif response.status_code == 429:
            retry_after = int(response.headers.get('Retry-After', 10))
            print(f"⏳ Rate limited. Waiting {retry_after}s...")
            time.sleep(retry_after)
            return make_api_request(url, params)
        return None
    except Exception as e:
        print(f"❌ Error: {e}")
        return None

def format_timestamp(timestamp_ms):
    return datetime.fromtimestamp(timestamp_ms / 1000).strftime('%Y-%m-%d %H:%M:%S')

def format_unit_info(unit):
    """Format thông tin chi tiết của một unit"""
    name = unit.get('character_id', 'Unknown')
    tier = unit.get('tier', 1)  # Star level (1-3)
    rarity = unit.get('rarity', 0)  # Cost (0=1cost, 1=2cost, etc)
    items = unit.get('itemNames', [])  # Item names
    
    # Rarity to cost mapping
    cost = rarity + 1
    
    # Format items
    items_str = '+'.join(items) if items else 'No items'
    
    return {
        'name': name,
        'tier': tier,
        'cost': cost,
        'items': items_str,
        'item_count': len(items)
    }

print("✅ Functions loaded!")

✅ Functions loaded!

In [20]:
# ========================================
# CELL 3: FETCH LEADERBOARD
# ========================================

print("🏆 Fetching TFT Leaderboard...\n")

all_players = []

url = f"https://{PLATFORM}.api.riotgames.com/tft/league/v1/challenger"
data = make_api_request(url)
if data:
    entries = data.get('entries', [])
    for e in entries:
        e['tier'] = 'CHALLENGER'
        all_players.append(e)
    print(f"✅ Challenger: {len(entries)}")

if len(all_players) < TOP_N:
    url = f"https://{PLATFORM}.api.riotgames.com/tft/league/v1/grandmaster"
    data = make_api_request(url)
    if data:
        entries = data.get('entries', [])
        for e in entries:
            e['tier'] = 'GRANDMASTER'
            all_players.append(e)
        print(f"✅ Grandmaster: {len(entries)}")

all_players = sorted(all_players, key=lambda x: x.get('leaguePoints', 0), reverse=True)
top_players = all_players[:TOP_N]

print(f"\n🏆 Top {len(top_players)} selected!")

🏆 Fetching TFT Leaderboard...

✅ Challenger: 450

🏆 Top 70 selected!

In [21]:
# ========================================
# CELL 4: GET RIOT IDs
# ========================================

print("📋 Fetching Riot IDs...\n")

top_players_detailed = []

for i, player in enumerate(top_players, 1):
    puuid = player.get('puuid')
    print(f"⏳ [{i}/{len(top_players)}] ", end="")
    
    if puuid:
        account_url = f"https://{REGION_ACCOUNT}.api.riotgames.com/riot/account/v1/accounts/by-puuid/{puuid}"
        account_data = make_api_request(account_url)
        
        if account_data:
            game_name = account_data.get('gameName', 'Unknown')
            tag_line = account_data.get('tagLine', 'VN2')
            riot_id = f"{game_name}#{tag_line}"
            
            info = {
                'rank': i,
                'riot_id': riot_id,
                'game_name': game_name,
                'tag_line': tag_line,
                'tier': player.get('tier'),
                'lp': player.get('leaguePoints', 0),
                'wins': player.get('wins', 0),
                'losses': player.get('losses', 0),
                'puuid': puuid
            }
            info['total_games'] = info['wins'] + info['losses']
            info['win_rate'] = round(info['wins'] / info['total_games'] * 100, 1) if info['total_games'] > 0 else 0
            
            top_players_detailed.append(info)
            print(f"✅ {riot_id} ({info['lp']} LP)")
        else:
            print(f"❌ Failed")
    else:
        print(f"❌ No PUUID")
    
    time.sleep(0.3)

print(f"\n✅ Got {len(top_players_detailed)} players!")

📋 Fetching Riot IDs...

⏳ [1/70] ✅ Hoàng Đế Shurima#2911 (2103 LP)
⏳ [2/70] ✅ EA7 longbentre#0910 (1956 LP)
⏳ [3/70] ✅ k3tdc#1st (1898 LP)
⏳ [4/70] ✅ HnZ Luckyboiz#0912 (1859 LP)
⏳ [5/70] ✅ Chunj1#chun (1851 LP)
⏳ [6/70] ✅ TìmLạiChínhMình#0907 (1785 LP)
⏳ [7/70] ✅ YBY1#0615 (1747 LP)
⏳ [8/70] ✅ Kharik#1403 (1720 LP)
⏳ [9/70] ✅ Vô Ám Giả#1982 (1656 LP)
⏳ [10/70] ✅ VP Lê Chuyên#2311 (1650 LP)
⏳ [11/70] ✅ this game sucks#2501 (1647 LP)
⏳ [12/70] ✅ TrungNguyen#257 (1640 LP)
⏳ [13/70] ✅ BBQ FEEDLATAO#2508 (1640 LP)
⏳ [14/70] ✅ VP Maris#Maris (1636 LP)
⏳ [15/70] ✅ GD Royal#1704 (1595 LP)
⏳ [16/70] ✅ Mọc 6 Túi#n6m (1588 LP)
⏳ [17/70] ✅ VP Succulento#poggo (1561 LP)
⏳ [18/70] ✅ Quỷ Vương Đây#6262 (1549 LP)
⏳ [19/70] ✅ changes#DVu (1548 LP)
⏳ [20/70] ✅ Bánh Xíu Páo#2605 (1548 LP)
⏳ [21/70] ✅ HnZ  sơnsmaill#JAV (1548 LP)
⏳ [22/70] ✅ MeoM3o#3636 (1541 LP)
⏳ [23/70] ✅ SSC D2JP#1129 (1531 LP)
⏳ [24/70] ✅ Killua Zoldyc#1999 (1527 LP)
⏳ [25/70] ✅ MG Final#CKTG (1527 LP)
⏳ [26/70] ✅ Kashtira Fenrir#hanss (1524 LP)
⏳ [27/70] ✅ Dean#1711 (1523 LP)
⏳ [28/70] ✅ DR Chase#0612 (1517 LP)
⏳ [29/70] ✅ KNG Cchh#1005 (1516 LP)
⏳ [30/70] ✅ Stillness1#0910 (1511 LP)
⏳ [31/70] ✅ HND TFT#1702 (1505 LP)
⏳ [32/70] ✅ Quang TX#1997 (1504 LP)
⏳ [33/70] ✅ nothing to lose#lth (1504 LP)
⏳ [34/70] ✅ DeeA#0801 (1501 LP)
⏳ [35/70] ✅ nguyenvux#vux (1497 LP)
⏳ [36/70] ✅ Trúc Cơ Sơ Kỳ#han1 (1495 LP)
⏳ [37/70] ✅ Sb Yunabi#Upppp (1489 LP)
⏳ [38/70] ✅ baenicaa#0311 (1487 LP)
⏳ [39/70] ✅ iCeEmperoz#mind (1486 LP)
⏳ [40/70] ✅ A Tẩm#1610 (1475 LP)
⏳ [41/70] ✅ Ước gì bớt đẳng#010 (1468 LP)
⏳ [42/70] ✅ MF xiaoyi#6868 (1460 LP)
⏳ [43/70] ✅ SW Llaih#Hiast (1456 LP)
⏳ [44/70] ✅ RRQ Asta#0497 (1452 LP)
⏳ [45/70] ✅ Sb flaw#ptqa (1450 LP)
⏳ [46/70] ✅ KND Last Dance#Lugh1 (1447 LP)
⏳ [47/70] ✅ HUST thôi#vn2 (1447 LP)
⏳ [48/70] ✅ Minorita#ducpl (1441 LP)
⏳ [49/70] ✅ JayDee#1509 (1440 LP)
⏳ [50/70] ✅ Marcus1#1107 (1429 LP)
⏳ [51/70] ✅ Gián Chết Trôi#172 (1426 LP)
⏳ [52/70] ✅ BéngThihi#0801 (1424 LP)
⏳ [53/70] ✅ Chunj2#chun (1420 LP)
⏳ [54/70] ✅ BọSiêuRì#simp (1419 LP)
⏳ [55/70] ✅ TOP1 CKTG#7777 (1415 LP)
⏳ [56/70] ✅ chihuyconga#rumeo (1414 LP)
⏳ [57/70] ✅ GD Khar1ch#611 (1411 LP)
⏳ [58/70] ✅ Arizona K#2607 (1401 LP)
⏳ [59/70] ✅ Em Dứa#2310 (1396 LP)
⏳ [60/70] ✅ dohaianh1996bn#0104 (1395 LP)
⏳ [61/70] ✅ Neekotine#minh (1393 LP)
⏳ [62/70] ✅ wowlon#4444 (1390 LP)
⏳ [63/70] ✅ Alex Đi CKTG#1611 (1389 LP)
⏳ [64/70] ✅ KOS No1 Lobby#BB1 (1382 LP)
⏳ [65/70] ✅ KAQ Destiny#Desti (1379 LP)
⏳ [66/70] ✅ Em Chè đi CKTG#3007 (1377 LP)
⏳ [67/70] ✅ ynwxx#2105 (1368 LP)
⏳ [68/70] ✅ LifeSquare#2265 (1363 LP)
⏳ [69/70] ✅ Vic1#1309 (1361 LP)
⏳ [70/70] ✅ MF Mèo Hor1#colen (1359 LP)

✅ Got 70 players!

In [22]:
# ========================================
# CELL 5: DISPLAY LEADERBOARD
# ========================================

leaderboard_df = pd.DataFrame(top_players_detailed)

if len(leaderboard_df) > 0:
    print(f"\n🏆 TFT LEADERBOARD - VN2 - TOP {len(leaderboard_df)}\n")
    pd.set_option('display.max_rows', 50)
    display(leaderboard_df[['rank', 'riot_id', 'tier', 'lp', 'wins', 'losses', 'win_rate', 'total_games']])

🏆 TFT LEADERBOARD - VN2 - TOP 70

,rank,riot_id,tier,lp,wins,losses,win_rate,total_games
0,1,Hoàng Đế Shurima#2911,CHALLENGER,2103,249,100,71.3,349
1,2,EA7 longbentre#0910,CHALLENGER,1956,590,339,63.5,929
2,3,k3tdc#1st,CHALLENGER,1898,271,154,63.8,425
3,4,HnZ Luckyboiz#0912,CHALLENGER,1859,388,195,66.6,583
4,5,Chunj1#chun,CHALLENGER,1851,445,272,62.1,717
...,...,...,...,...,...,...,...,...
65,66,Em Chè đi CKTG#3007,CHALLENGER,1377,403,277,59.3,680
66,67,ynwxx#2105,CHALLENGER,1368,362,243,59.8,605
67,68,LifeSquare#2265,CHALLENGER,1363,493,429,53.5,922
68,69,Vic1#1309,CHALLENGER,1361,553,362,60.4,915
69,70,MF Mèo Hor1#colen,CHALLENGER,1359,468,387,54.7,855

In [23]:
# ========================================
# CELL 6: FETCH MATCH HISTORY (với unit details)
# ========================================

if len(top_players_detailed) == 0:
    print("⚠️ No players to fetch.")
else:
    print(f"📊 Fetching match history ({MATCH_COUNT_PER_PLAYER} matches/player)...\n")
    
    all_player_stats = []  # Match stats
    all_unit_details = []  # Unit details per match
    
    for player in top_players_detailed:
        puuid = player['puuid']
        riot_id = player['riot_id']
        rank = player['rank']
        
        print(f"🎮 [{rank}] {riot_id} ", end="")
        
        match_url = f"https://{REGION_MATCH}.api.riotgames.com/tft/match/v1/matches/by-puuid/{puuid}/ids"
        match_ids = make_api_request(match_url, {"count": MATCH_COUNT_PER_PLAYER})
        
        if not match_ids:
            print("⚠️ No matches")
            continue
        
        matches_fetched = 0
        for match_id in match_ids:
            detail_url = f"https://{REGION_MATCH}.api.riotgames.com/tft/match/v1/matches/{match_id}"
            match_detail = make_api_request(detail_url)
            
            if match_detail:
                info = match_detail.get('info', {})
                for p in info.get('participants', []):
                    if p.get('puuid') == puuid:
                        # Traits
                        traits = [t['name'] for t in p.get('traits', []) if t.get('tier_current', 0) > 0]
                        
                        # Units với chi tiết
                        units = p.get('units', [])
                        unit_names = []
                        unit_details_str = []
                        
                        for unit in units:
                            unit_info = format_unit_info(unit)
                            unit_names.append(unit_info['name'])
                            
                            # Format: Name(tier★, cost$, items)
                            detail = f"{unit_info['name']}({unit_info['tier']}★{unit_info['cost']}$)"
                            if unit_info['item_count'] > 0:
                                detail += f"[{unit_info['items']}]"
                            unit_details_str.append(detail)
                            
                            # Lưu chi tiết riêng cho phân tích
                            all_unit_details.append({
                                'riot_id': riot_id,
                                'match_id': match_id,
                                'placement': p.get('placement'),
                                'unit_name': unit_info['name'],
                                'unit_tier': unit_info['tier'],
                                'unit_cost': unit_info['cost'],
                                'unit_items': unit_info['items'],
                                'item_count': unit_info['item_count']
                            })
                        
                        # Match stats
                        all_player_stats.append({
                            'riot_id': riot_id,
                            'leaderboard_rank': rank,
                            'match_id': match_id,
                            'datetime': format_timestamp(info.get('game_datetime', 0)),
                            'placement': p.get('placement'),
                            'level': p.get('level'),
                            'traits': ', '.join(traits[:5]),
                            'units': ', '.join(unit_names),
                            'units_detailed': ' | '.join(unit_details_str),
                            'num_units': len(units)
                        })
                        matches_fetched += 1
                        break
            time.sleep(0.25)
        
        print(f"✅ {matches_fetched} matches")
    
    print(f"\n✅ Total: {len(all_player_stats)} matches, {len(all_unit_details)} unit records")

📊 Fetching match history (200 matches/player)...

🎮 [1] Hoàng Đế Shurima#2911 ✅ 200 matches
🎮 [2] EA7 longbentre#0910 ✅ 200 matches
🎮 [3] k3tdc#1st ⏳ Rate limited. Waiting 12s...
✅ 200 matches
🎮 [4] HnZ Luckyboiz#0912 ⏳ Rate limited. Waiting 69s...
⏳ Rate limited. Waiting 58s...
⏳ Rate limited. Waiting 55s...
⏳ Rate limited. Waiting 55s...
✅ 200 matches
🎮 [5] Chunj1#chun ⏳ Rate limited. Waiting 68s...
⏳ Rate limited. Waiting 66s...
⏳ Rate limited. Waiting 64s...
⏳ Rate limited. Waiting 54s...
⏳ Rate limited. Waiting 63s...
⏳ Rate limited. Waiting 67s...
✅ 200 matches
🎮 [6] TìmLạiChínhMình#0907 ⏳ Rate limited. Waiting 61s...
⏳ Rate limited. Waiting 69s...
⏳ Rate limited. Waiting 68s...
⏳ Rate limited. Waiting 65s...
⏳ Rate limited. Waiting 66s...
✅ 200 matches
🎮 [7] YBY1#0615 ⏳ Rate limited. Waiting 66s...
⏳ Rate limited. Waiting 61s...
⏳ Rate limited. Waiting 59s...
⏳ Rate limited. Waiting 61s...
⏳ Rate limited. Waiting 56s...
✅ 200 matches
🎮 [8] Kharik#1403 ⏳ Rate limited. Waiting 68s...
⏳ Rate limited. Waiting 65s...
⏳ Rate limited. Waiting 67s...
⏳ Rate limited. Waiting 63s...
⏳ Rate limited. Waiting 59s...
✅ 200 matches
🎮 [9] Vô Ám Giả#1982 ⏳ Rate limited. Waiting 52s...
⏳ Rate limited. Waiting 56s...
⏳ Rate limited. Waiting 59s...
⏳ Rate limited. Waiting 65s...
⏳ Rate limited. Waiting 69s...
✅ 200 matches
🎮 [10] VP Lê Chuyên#2311 ⏳ Rate limited. Waiting 59s...
⏳ Rate limited. Waiting 67s...
⏳ Rate limited. Waiting 67s...
⏳ Rate limited. Waiting 71s...
⏳ Rate limited. Waiting 71s...
✅ 200 matches
🎮 [11] this game sucks#2501 ⏳ Rate limited. Waiting 66s...
⏳ Rate limited. Waiting 72s...
⏳ Rate limited. Waiting 69s...
⏳ Rate limited. Waiting 68s...
⏳ Rate limited. Waiting 68s...
✅ 200 matches
🎮 [12] TrungNguyen#257 ⏳ Rate limited. Waiting 65s...
⏳ Rate limited. Waiting 68s...
⏳ Rate limited. Waiting 70s...
⏳ Rate limited. Waiting 69s...
⏳ Rate limited. Waiting 71s...
⏳ Rate limited. Waiting 69s...
✅ 200 matches
🎮 [13] BBQ FEEDLATAO#2508 ⏳ Rate limited. Waiting 69s...
⏳ Rate limited. Waiting 64s...
⏳ Rate limited. Waiting 70s...
⏳ Rate limited. Waiting 66s...
⏳ Rate limited. Waiting 71s...
✅ 200 matches
🎮 [14] VP Maris#Maris ⏳ Rate limited. Waiting 66s...
⏳ Rate limited. Waiting 71s...
⏳ Rate limited. Waiting 71s...
⏳ Rate limited. Waiting 69s...
⏳ Rate limited. Waiting 64s...
✅ 200 matches
🎮 [15] GD Royal#1704 ⏳ Rate limited. Waiting 69s...
⏳ Rate limited. Waiting 68s...
❌ Error: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
❌ Error: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
❌ Error: HTTPSConnectionPool(host='sea.api.riotgames.com', port=443): Max retries exceeded with url: /tft/match/v1/matches/VN2_1216921014 (Caused by NameResolutionError("HTTPSConnection(host='sea.api.riotgames.com', port=443): Failed to resolve 'sea.api.riotgames.com' ([Errno 11001] getaddrinfo failed)"))
❌ Error: HTTPSConnectionPool(host='sea.api.riotgames.com', port=443): Max retries exceeded with url: /tft/match/v1/matches/VN2_1216883346 (Caused by NameResolutionError("HTTPSConnection(host='sea.api.riotgames.com', port=443): Failed to resolve 'sea.api.riotgames.com' ([Errno 11001] getaddrinfo failed)"))
❌ Error: HTTPSConnectionPool(host='sea.api.riotgames.com', port=443): Max retries exceeded with url: /tft/match/v1/matches/VN2_1216751252 (Caused by NameResolutionError("HTTPSConnection(host='sea.api.riotgames.com', port=443): Failed to resolve 'sea.api.riotgames.com' ([Errno 11001] getaddrinfo failed)"))
❌ Error: HTTPSConnectionPool(host='sea.api.riotgames.com', port=443): Max retries exceeded with url: /tft/match/v1/matches/VN2_1216696376 (Caused by NameResolutionError("HTTPSConnection(host='sea.api.riotgames.com', port=443): Failed to resolve 'sea.api.riotgames.com' ([Errno 11001] getaddrinfo failed)"))
❌ Error: HTTPSConnectionPool(host='sea.api.riotgames.com', port=443): Max retries exceeded with url: /tft/match/v1/matches/VN2_1216177216 (Caused by NameResolutionError("HTTPSConnection(host='sea.api.riotgames.com', port=443): Failed to resolve 'sea.api.riotgames.com' ([Errno 11001] getaddrinfo failed)"))
❌ Error: HTTPSConnectionPool(host='sea.api.riotgames.com', port=443): Max retries exceeded with url: /tft/match/v1/matches/VN2_1216114614 (Caused by NameResolutionError("HTTPSConnection(host='sea.api.riotgames.com', port=443): Failed to resolve 'sea.api.riotgames.com' ([Errno 11001] getaddrinfo failed)"))
❌ Error: HTTPSConnectionPool(host='sea.api.riotgames.com', port=443): Max retries exceeded with url: /tft/match/v1/matches/VN2_1216066108 (Caused by NameResolutionError("HTTPSConnection(host='sea.api.riotgames.com', port=443): Failed to resolve 'sea.api.riotgames.com' ([Errno 11001] getaddrinfo failed)"))
❌ Error: HTTPSConnectionPool(host='sea.api.riotgames.com', port=443): Max retries exceeded with url: /tft/match/v1/matches/VN2_1215984311 (Caused by NameResolutionError("HTTPSConnection(host='sea.api.riotgames.com', port=443): Failed to resolve 'sea.api.riotgames.com' ([Errno 11001] getaddrinfo failed)"))
❌ Error: HTTPSConnectionPool(host='sea.api.riotgames.com', port=443): Max retries exceeded with url: /tft/match/v1/matches/VN2_1215914035 (Caused by NameResolutionError("HTTPSConnection(host='sea.api.riotgames.com', port=443): Failed to resolve 'sea.api.riotgames.com' ([Errno 11001] getaddrinfo failed)"))
❌ Error: HTTPSConnectionPool(host='sea.api.riotgames.com', port=443): Max retries exceeded with url: /tft/match/v1/matches/VN2_1215824684 (Caused by NameResolutionError("HTTPSConnection(host='sea.api.riotgames.com', port=443): Failed to resolve 'sea.api.riotgames.com' ([Errno 11001] getaddrinfo failed)"))
❌ Error: HTTPSConnectionPool(host='sea.api.riotgames.com', port=443): Max retries exceeded with url: /tft/match/v1/matches/VN2_1215762038 (Caused by NameResolutionError("HTTPSConnection(host='sea.api.riotgames.com', port=443): Failed to resolve 'sea.api.riotgames.com' ([Errno 11001] getaddrinfo failed)"))
❌ Error: HTTPSConnectionPool(host='sea.api.riotgames.com', port=443): Max retries exceeded with url: /tft/match/v1/matches/VN2_1215669546 (Caused by NameResolutionError("HTTPSConnection(host='sea.api.riotgames.com', port=443): Failed to resolve 'sea.api.riotgames.com' ([Errno 11001] getaddrinfo failed)"))
❌ Error: HTTPSConnectionPool(host='sea.api.riotgames.com', port=443): Max retries exceeded with url: /tft/match/v1/matches/VN2_1214481269 (Caused by NameResolutionError("HTTPSConnection(host='sea.api.riotgames.com', port=443): Failed to resolve 'sea.api.riotgames.com' ([Errno 11001] getaddrinfo failed)"))
❌ Error: HTTPSConnectionPool(host='sea.api.riotgames.com', port=443): Max retries exceeded with url: /tft/match/v1/matches/VN2_1214404507 (Caused by NameResolutionError("HTTPSConnection(host='sea.api.riotgames.com', port=443): Failed to resolve 'sea.api.riotgames.com' ([Errno 11001] getaddrinfo failed)"))
❌ Error: HTTPSConnectionPool(host='sea.api.riotgames.com', port=443): Max retries exceeded with url: /tft/match/v1/matches/VN2_1214326938 (Caused by NameResolutionError("HTTPSConnection(host='sea.api.riotgames.com', port=443): Failed to resolve 'sea.api.riotgames.com' ([Errno 11001] getaddrinfo failed)"))
❌ Error: HTTPSConnectionPool(host='sea.api.riotgames.com', port=443): Max retries exceeded with url: /tft/match/v1/matches/VN2_1214261489 (Caused by NameResolutionError("HTTPSConnection(host='sea.api.riotgames.com', port=443): Failed to resolve 'sea.api.riotgames.com' ([Errno 11001] getaddrinfo failed)"))
❌ Error: HTTPSConnectionPool(host='sea.api.riotgames.com', port=443): Max retries exceeded with url: /tft/match/v1/matches/VN2_1214197096 (Caused by NameResolutionError("HTTPSConnection(host='sea.api.riotgames.com', port=443): Failed to resolve 'sea.api.riotgames.com' ([Errno 11001] getaddrinfo failed)"))
❌ Error: HTTPSConnectionPool(host='sea.api.riotgames.com', port=443): Max retries exceeded with url: /tft/match/v1/matches/VN2_1214093443 (Caused by NameResolutionError("HTTPSConnection(host='sea.api.riotgames.com', port=443): Failed to resolve 'sea.api.riotgames.com' ([Errno 11001] getaddrinfo failed)"))
❌ Error: HTTPSConnectionPool(host='sea.api.riotgames.com', port=443): Max retries exceeded with url: /tft/match/v1/matches/VN2_1214051455 (Caused by NameResolutionError("HTTPSConnection(host='sea.api.riotgames.com', port=443): Failed to resolve 'sea.api.riotgames.com' ([Errno 11001] getaddrinfo failed)"))
❌ Error: HTTPSConnectionPool(host='sea.api.riotgames.com', port=443): Max retries exceeded with url: /tft/match/v1/matches/VN2_1214006501 (Caused by NameResolutionError("HTTPSConnection(host='sea.api.riotgames.com', port=443): Failed to resolve 'sea.api.riotgames.com' ([Errno 11001] getaddrinfo failed)"))
❌ Error: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
❌ Error: HTTPSConnectionPool(host='sea.api.riotgames.com', port=443): Max retries exceeded with url: /tft/match/v1/matches/VN2_1213741158 (Caused by NewConnectionError("HTTPSConnection(host='sea.api.riotgames.com', port=443): Failed to establish a new connection: [WinError 10065] A socket operation was attempted to an unreachable host"))
❌ Error: HTTPSConnectionPool(host='sea.api.riotgames.com', port=443): Max retries exceeded with url: /tft/match/v1/matches/VN2_1213690479 (Caused by NameResolutionError("HTTPSConnection(host='sea.api.riotgames.com', port=443): Failed to resolve 'sea.api.riotgames.com' ([Errno 11001] getaddrinfo failed)"))
❌ Error: HTTPSConnectionPool(host='sea.api.riotgames.com', port=443): Max retries exceeded with url: /tft/match/v1/matches/VN2_1213601182 (Caused by NameResolutionError("HTTPSConnection(host='sea.api.riotgames.com', port=443): Failed to resolve 'sea.api.riotgames.com' ([Errno 11001] getaddrinfo failed)"))
❌ Error: HTTPSConnectionPool(host='sea.api.riotgames.com', port=443): Max retries exceeded with url: /tft/match/v1/matches/VN2_1213563408 (Caused by NameResolutionError("HTTPSConnection(host='sea.api.riotgames.com', port=443): Failed to resolve 'sea.api.riotgames.com' ([Errno 11001] getaddrinfo failed)"))
❌ Error: HTTPSConnectionPool(host='sea.api.riotgames.com', port=443): Max retries exceeded with url: /tft/match/v1/matches/VN2_1213517162 (Caused by NameResolutionError("HTTPSConnection(host='sea.api.riotgames.com', port=443): Failed to resolve 'sea.api.riotgames.com' ([Errno 11001] getaddrinfo failed)"))
❌ Error: HTTPSConnectionPool(host='sea.api.riotgames.com', port=443): Max retries exceeded with url: /tft/match/v1/matches/VN2_1213482103 (Caused by NameResolutionError("HTTPSConnection(host='sea.api.riotgames.com', port=443): Failed to resolve 'sea.api.riotgames.com' ([Errno 11001] getaddrinfo failed)"))
❌ Error: HTTPSConnectionPool(host='sea.api.riotgames.com', port=443): Max retries exceeded with url: /tft/match/v1/matches/VN2_1213442008 (Caused by NameResolutionError("HTTPSConnection(host='sea.api.riotgames.com', port=443): Failed to resolve 'sea.api.riotgames.com' ([Errno 11001] getaddrinfo failed)"))
❌ Error: HTTPSConnectionPool(host='sea.api.riotgames.com', port=443): Max retries exceeded with url: /tft/match/v1/matches/VN2_1213402022 (Caused by NameResolutionError("HTTPSConnection(host='sea.api.riotgames.com', port=443): Failed to resolve 'sea.api.riotgames.com' ([Errno 11001] getaddrinfo failed)"))
❌ Error: HTTPSConnectionPool(host='sea.api.riotgames.com', port=443): Max retries exceeded with url: /tft/match/v1/matches/VN2_1213141907 (Caused by NameResolutionError("HTTPSConnection(host='sea.api.riotgames.com', port=443): Failed to resolve 'sea.api.riotgames.com' ([Errno 11001] getaddrinfo failed)"))
❌ Error: HTTPSConnectionPool(host='sea.api.riotgames.com', port=443): Max retries exceeded with url: /tft/match/v1/matches/VN2_1213122419 (Caused by NameResolutionError("HTTPSConnection(host='sea.api.riotgames.com', port=443): Failed to resolve 'sea.api.riotgames.com' ([Errno 11001] getaddrinfo failed)"))
❌ Error: HTTPSConnectionPool(host='sea.api.riotgames.com', port=443): Max retries exceeded with url: /tft/match/v1/matches/VN2_1213092421 (Caused by NameResolutionError("HTTPSConnection(host='sea.api.riotgames.com', port=443): Failed to resolve 'sea.api.riotgames.com' ([Errno 11001] getaddrinfo failed)"))
❌ Error: HTTPSConnectionPool(host='sea.api.riotgames.com', port=443): Max retries exceeded with url: /tft/match/v1/matches/VN2_1213056857 (Caused by NameResolutionError("HTTPSConnection(host='sea.api.riotgames.com', port=443): Failed to resolve 'sea.api.riotgames.com' ([Errno 11001] getaddrinfo failed)"))
❌ Error: HTTPSConnectionPool(host='sea.api.riotgames.com', port=443): Max retries exceeded with url: /tft/match/v1/matches/VN2_1213015080 (Caused by NameResolutionError("HTTPSConnection(host='sea.api.riotgames.com', port=443): Failed to resolve 'sea.api.riotgames.com' ([Errno 11001] getaddrinfo failed)"))
❌ Error: HTTPSConnectionPool(host='sea.api.riotgames.com', port=443): Max retries exceeded with url: /tft/match/v1/matches/VN2_1212965738 (Caused by NameResolutionError("HTTPSConnection(host='sea.api.riotgames.com', port=443): Failed to resolve 'sea.api.riotgames.com' ([Errno 11001] getaddrinfo failed)"))
❌ Error: HTTPSConnectionPool(host='sea.api.riotgames.com', port=443): Max retries exceeded with url: /tft/match/v1/matches/VN2_1212909979 (Caused by NameResolutionError("HTTPSConnection(host='sea.api.riotgames.com', port=443): Failed to resolve 'sea.api.riotgames.com' ([Errno 11001] getaddrinfo failed)"))
❌ Error: HTTPSConnectionPool(host='sea.api.riotgames.com', port=443): Max retries exceeded with url: /tft/match/v1/matches/VN2_1212847132 (Caused by NameResolutionError("HTTPSConnection(host='sea.api.riotgames.com', port=443): Failed to resolve 'sea.api.riotgames.com' ([Errno 11001] getaddrinfo failed)"))
❌ Error: HTTPSConnectionPool(host='sea.api.riotgames.com', port=443): Max retries exceeded with url: /tft/match/v1/matches/VN2_1212779375 (Caused by NameResolutionError("HTTPSConnection(host='sea.api.riotgames.com', port=443): Failed to resolve 'sea.api.riotgames.com' ([Errno 11001] getaddrinfo failed)"))
❌ Error: HTTPSConnectionPool(host='sea.api.riotgames.com', port=443): Max retries exceeded with url: /tft/match/v1/matches/VN2_1212720593 (Caused by NameResolutionError("HTTPSConnection(host='sea.api.riotgames.com', port=443): Failed to resolve 'sea.api.riotgames.com' ([Errno 11001] getaddrinfo failed)"))
❌ Error: HTTPSConnectionPool(host='sea.api.riotgames.com', port=443): Max retries exceeded with url: /tft/match/v1/matches/VN2_1212649715 (Caused by NameResolutionError("HTTPSConnection(host='sea.api.riotgames.com', port=443): Failed to resolve 'sea.api.riotgames.com' ([Errno 11001] getaddrinfo failed)"))
❌ Error: HTTPSConnectionPool(host='sea.api.riotgames.com', port=443): Max retries exceeded with url: /tft/match/v1/matches/VN2_1212576153 (Caused by NameResolutionError("HTTPSConnection(host='sea.api.riotgames.com', port=443): Failed to resolve 'sea.api.riotgames.com' ([Errno 11001] getaddrinfo failed)"))
❌ Error: HTTPSConnectionPool(host='sea.api.riotgames.com', port=443): Max retries exceeded with url: /tft/match/v1/matches/VN2_1212251544 (Caused by NameResolutionError("HTTPSConnection(host='sea.api.riotgames.com', port=443): Failed to resolve 'sea.api.riotgames.com' ([Errno 11001] getaddrinfo failed)"))
❌ Error: HTTPSConnectionPool(host='sea.api.riotgames.com', port=443): Max retries exceeded with url: /tft/match/v1/matches/VN2_1212200204 (Caused by NameResolutionError("HTTPSConnection(host='sea.api.riotgames.com', port=443): Failed to resolve 'sea.api.riotgames.com' ([Errno 11001] getaddrinfo failed)"))
❌ Error: HTTPSConnectionPool(host='sea.api.riotgames.com', port=443): Max retries exceeded with url: /tft/match/v1/matches/VN2_1212134904 (Caused by NameResolutionError("HTTPSConnection(host='sea.api.riotgames.com', port=443): Failed to resolve 'sea.api.riotgames.com' ([Errno 11001] getaddrinfo failed)"))
❌ Error: HTTPSConnectionPool(host='sea.api.riotgames.com', port=443): Max retries exceeded with url: /tft/match/v1/matches/VN2_1212078899 (Caused by NameResolutionError("HTTPSConnection(host='sea.api.riotgames.com', port=443): Failed to resolve 'sea.api.riotgames.com' ([Errno 11001] getaddrinfo failed)"))
❌ Error: HTTPSConnectionPool(host='sea.api.riotgames.com', port=443): Max retries exceeded with url: /tft/match/v1/matches/VN2_1212023630 (Caused by NameResolutionError("HTTPSConnection(host='sea.api.riotgames.com', port=443): Failed to resolve 'sea.api.riotgames.com' ([Errno 11001] getaddrinfo failed)"))
❌ Error: HTTPSConnectionPool(host='sea.api.riotgames.com', port=443): Max retries exceeded with url: /tft/match/v1/matches/VN2_1211952621 (Caused by NameResolutionError("HTTPSConnection(host='sea.api.riotgames.com', port=443): Failed to resolve 'sea.api.riotgames.com' ([Errno 11001] getaddrinfo failed)"))
❌ Error: HTTPSConnectionPool(host='sea.api.riotgames.com', port=443): Max retries exceeded with url: /tft/match/v1/matches/VN2_1211914243 (Caused by NameResolutionError("HTTPSConnection(host='sea.api.riotgames.com', port=443): Failed to resolve 'sea.api.riotgames.com' ([Errno 11001] getaddrinfo failed)"))
❌ Error: HTTPSConnectionPool(host='sea.api.riotgames.com', port=443): Max retries exceeded with url: /tft/match/v1/matches/VN2_1211859106 (Caused by NameResolutionError("HTTPSConnection(host='sea.api.riotgames.com', port=443): Failed to resolve 'sea.api.riotgames.com' ([Errno 11001] getaddrinfo failed)"))
❌ Error: HTTPSConnectionPool(host='sea.api.riotgames.com', port=443): Max retries exceeded with url: /tft/match/v1/matches/VN2_1211811344 (Caused by NameResolutionError("HTTPSConnection(host='sea.api.riotgames.com', port=443): Failed to resolve 'sea.api.riotgames.com' ([Errno 11001] getaddrinfo failed)"))
❌ Error: HTTPSConnectionPool(host='sea.api.riotgames.com', port=443): Max retries exceeded with url: /tft/match/v1/matches/VN2_1211767379 (Caused by NameResolutionError("HTTPSConnection(host='sea.api.riotgames.com', port=443): Failed to resolve 'sea.api.riotgames.com' ([Errno 11001] getaddrinfo failed)"))
❌ Error: HTTPSConnectionPool(host='sea.api.riotgames.com', port=443): Max retries exceeded with url: /tft/match/v1/matches/VN2_1211713784 (Caused by NameResolutionError("HTTPSConnection(host='sea.api.riotgames.com', port=443): Failed to resolve 'sea.api.riotgames.com' ([Errno 11001] getaddrinfo failed)"))
❌ Error: HTTPSConnectionPool(host='sea.api.riotgames.com', port=443): Max retries exceeded with url: /tft/match/v1/matches/VN2_1211674207 (Caused by NameResolutionError("HTTPSConnection(host='sea.api.riotgames.com', port=443): Failed to resolve 'sea.api.riotgames.com' ([Errno 11001] getaddrinfo failed)"))
❌ Error: HTTPSConnectionPool(host='sea.api.riotgames.com', port=443): Max retries exceeded with url: /tft/match/v1/matches/VN2_1211356705 (Caused by NameResolutionError("HTTPSConnection(host='sea.api.riotgames.com', port=443): Failed to resolve 'sea.api.riotgames.com' ([Errno 11001] getaddrinfo failed)"))
❌ Error: HTTPSConnectionPool(host='sea.api.riotgames.com', port=443): Max retries exceeded with url: /tft/match/v1/matches/VN2_1211310375 (Caused by NameResolutionError("HTTPSConnection(host='sea.api.riotgames.com', port=443): Failed to resolve 'sea.api.riotgames.com' ([Errno 11001] getaddrinfo failed)"))
❌ Error: HTTPSConnectionPool(host='sea.api.riotgames.com', port=443): Max retries exceeded with url: /tft/match/v1/matches/VN2_1211268319 (Caused by NameResolutionError("HTTPSConnection(host='sea.api.riotgames.com', port=443): Failed to resolve 'sea.api.riotgames.com' ([Errno 11001] getaddrinfo failed)"))
❌ Error: HTTPSConnectionPool(host='sea.api.riotgames.com', port=443): Max retries exceeded with url: /tft/match/v1/matches/VN2_1211190496 (Caused by NameResolutionError("HTTPSConnection(host='sea.api.riotgames.com', port=443): Failed to resolve 'sea.api.riotgames.com' ([Errno 11001] getaddrinfo failed)"))

In [14]:
# ========================================
# CELL 7: DISPLAY & SAVE DATA
# ========================================

match_df = pd.DataFrame(all_player_stats) if 'all_player_stats' in dir() and all_player_stats else pd.DataFrame()
unit_df = pd.DataFrame(all_unit_details) if 'all_unit_details' in dir() and all_unit_details else pd.DataFrame()

print("💾 Saving...\n")

# Save leaderboard
if len(leaderboard_df) > 0:
    filename = f"tft_leaderboard_{PLATFORM}_top{TOP_N}.csv"
    leaderboard_df.to_csv(filename, index=False, encoding='utf-8-sig')
    print(f"✅ {filename}")

# Save match history
if len(match_df) > 0:
    filename = f"tft_matches_{PLATFORM}_top{TOP_N}.csv"
    match_df.to_csv(filename, index=False, encoding='utf-8-sig')
    print(f"✅ {filename}")

# Save unit details
if len(unit_df) > 0:
    filename = f"tft_units_{PLATFORM}_top{TOP_N}.csv"
    unit_df.to_csv(filename, index=False, encoding='utf-8-sig')
    print(f"✅ {filename}")

print("\n📊 Match History Preview:")
if len(match_df) > 0:
    display(match_df[['riot_id', 'placement', 'level', 'units_detailed']].head(10))

print("\n📊 Unit Details Preview:")
if len(unit_df) > 0:
    display(unit_df.head(20))

print("\n🎉 Done!")

💾 Saving...

✅ tft_leaderboard_vn2_top40.csv
✅ tft_matches_vn2_top40.csv
✅ tft_units_vn2_top40.csv

📊 Match History Preview:

,riot_id,placement,level,units_detailed
0,Ước gì bớt đẳng#010,3,8,TFT16_Lulu(3★1$) | TFT16_Rumble(2★1$) | TFT16_...
1,Ước gì bớt đẳng#010,2,10,TFT16_Nautilus(2★3$) | TFT16_MissFortune(2★5$)...
2,Ước gì bớt đẳng#010,2,8,TFT16_JarvanIV(2★1$) | TFT16_Poppy(2★2$) | TFT...
3,Ước gì bớt đẳng#010,4,8,TFT16_JarvanIV(3★1$)[TFT_Item_AdaptiveHelm] | ...
4,Ước gì bớt đẳng#010,7,8,TFT16_Shen(2★1$)[TFT_Item_NegatronCloak] | TFT...
5,Ước gì bớt đẳng#010,4,9,TFT16_Neeko(2★2$)[TFT_Item_NegatronCloak] | TF...
6,Ước gì bớt đẳng#010,1,9,TFT16_Vi(2★2$) | TFT16_Orianna(2★2$) | TFT16_T...
7,Ước gì bớt đẳng#010,2,9,TFT16_Sion(2★2$) | TFT16_Gangplank(1★3$) | TFT...
8,Ước gì bớt đẳng#010,5,9,TFT16_Briar(1★1$) | TFT16_ChoGath(1★2$) | TFT1...
9,Ước gì bớt đẳng#010,7,5,TFT16_JarvanIV(1★1$) | TFT16_Vi(1★2$) | TFT16_...

📊 Unit Details Preview:

,riot_id,match_id,placement,unit_name,unit_tier,unit_cost,unit_items,item_count
0,Ước gì bớt đẳng#010,VN2_1239749291,3,TFT16_Lulu,3,1,No items,0
1,Ước gì bớt đẳng#010,VN2_1239749291,3,TFT16_Rumble,2,1,No items,0
2,Ước gì bớt đẳng#010,VN2_1239749291,3,TFT16_Teemo,2,2,No items,0
3,Ước gì bớt đẳng#010,VN2_1239749291,3,TFT16_Poppy,2,2,TFT_Item_ThiefsGloves+TFT_Item_JeweledGauntlet...,3
4,Ước gì bớt đẳng#010,VN2_1239749291,3,TFT16_Kobuko,3,3,TFT_Item_IonicSpark+TFT_Item_BrambleVest,2
5,Ước gì bớt đẳng#010,VN2_1239749291,3,TFT16_Kennen,3,3,TFT_Item_RedBuff+TFT_Item_Redemption+TFT_Item_...,3
6,Ước gì bớt đẳng#010,VN2_1239749291,3,TFT16_Veigar,3,5,TFT_Item_RabadonsDeathcap+TFT_Item_PowerGauntl...,3
7,Ước gì bớt đẳng#010,VN2_1239749291,3,TFT16_Fizz,3,5,TFT_Item_JeweledGauntlet+TFT_Item_UnstableConc...,3
8,Ước gì bớt đẳng#010,VN2_1239700948,2,TFT16_Nautilus,2,3,No items,0
9,Ước gì bớt đẳng#010,VN2_1239700948,2,TFT16_MissFortune,2,5,TFT_Item_PowerGauntlet+TFT_Item_GuinsoosRageblade,2
10,Ước gì bớt đẳng#010,VN2_1239700948,2,TFT16_Taric,1,5,No items,0
11,Ước gì bớt đẳng#010,VN2_1239700948,2,TFT16_Seraphine,1,5,No items,0
12,Ước gì bớt đẳng#010,VN2_1239700948,2,TFT16_Skarner,1,5,No items,0
13,Ước gì bớt đẳng#010,VN2_1239700948,2,TFT16_Swain,2,5,TFT16_Item_ZaunEmblemItem+TFT16_Item_IxtalEmbl...,3
14,Ước gì bớt đẳng#010,VN2_1239700948,2,TFT16_Azir,1,7,TFT_Item_ThiefsGloves+TFT_Item_EmptyBag+TFT_It...,3
15,Ước gì bớt đẳng#010,VN2_1239700948,2,TFT16_Fiddlesticks,1,7,TFT_Item_UnstableConcoction,1
16,Ước gì bớt đẳng#010,VN2_1239700948,2,TFT16_Lucian,1,7,TFT_Item_Morellonomicon+TFT_Item_StatikkShiv,2
17,Ước gì bớt đẳng#010,VN2_1239700948,2,TFT16_Shyvana,1,7,TFT_Item_ForceOfNature+TFT_Item_ForceOfNature,2
18,Ước gì bớt đẳng#010,VN2_1239700948,2,TFT16_Brock,2,8,TFT_Item_ThiefsGloves+TFT_Item_EmptyBag+TFT_It...,3
19,Ước gì bớt đẳng#010,VN2_1239700948,2,TFT16_Brock,2,8,TFT5_Item_AdaptiveHelmRadiant+TFT5_Item_Brambl...,3

🎉 Done!

In [15]:
# ========================================
# CELL 8: ANALYZE UNITS
# ========================================

if len(unit_df) > 0:
    print("📊 UNIT ANALYSIS\n")
    
    # Most used units
    print("🔥 Most Used Units:")
    unit_counts = unit_df['unit_name'].value_counts().head(15)
    for unit, count in unit_counts.items():
        print(f"   {unit}: {count}")
    
    # Most common 3-star units
    print("\n⭐ Most Common 3-Star Units:")
    three_star = unit_df[unit_df['unit_tier'] == 3]['unit_name'].value_counts().head(10)
    for unit, count in three_star.items():
        print(f"   {unit}: {count}")
    
    # Most common items
    print("\n🛡️ Most Common Items:")
    all_items = []
    for items_str in unit_df['unit_items'].dropna():
        if items_str and items_str != 'No items':
            items = items_str.split('+')
            all_items.extend(items)
    
    item_counts = pd.Series(all_items).value_counts().head(15)
    for item, count in item_counts.items():
        print(f"   {item}: {count}")
    
    # Units with most items
    print("\n🎯 Units with Most Items:")
    carry_units = unit_df[unit_df['item_count'] >= 3].groupby('unit_name').size().sort_values(ascending=False).head(10)
    for unit, count in carry_units.items():
        print(f"   {unit}: {count} times with 3+ items")

📊 UNIT ANALYSIS

🔥 Most Used Units:
   TFT16_Swain: 51
   TFT16_Vi: 45
   TFT16_Seraphine: 39
   TFT16_Taric: 38
   TFT16_Shyvana: 38
   TFT16_Wukong: 26
   TFT16_Azir: 25
   TFT16_Lucian: 24
   TFT16_Lissandra: 23
   TFT16_Braum: 22
   TFT16_Fiddlesticks: 21
   TFT16_Loris: 20
   TFT16_Neeko: 18
   TFT16_Sejuani: 18
   TFT16_Orianna: 17

⭐ Most Common 3-Star Units:
   TFT16_Kennen: 3
   TFT16_Neeko: 3
   TFT16_Orianna: 3
   TFT16_Lux: 2
   TFT16_MissFortune: 2
   TFT16_Qiyana: 2
   TFT16_Milio: 2
   TFT16_Bard: 2
   TFT16_TwistedFate: 2
   TFT16_Lulu: 1

🛡️ Most Common Items:
   TFT_Item_JeweledGauntlet: 66
   TFT_Item_SpearOfShojin: 48
   TFT_Item_ThiefsGloves: 46
   TFT_Item_GargoyleStoneplate: 42
   TFT_Item_FrozenHeart: 42
   TFT_Item_WarmogsArmor: 41
   TFT_Item_Leviathan: 37
   TFT_Item_Morellonomicon: 37
   TFT_Item_Redemption: 36
   TFT_Item_GuinsoosRageblade: 36
   TFT_Item_DragonsClaw: 36
   TFT_Item_InfinityEdge: 35
   TFT_Item_AdaptiveHelm: 35
   TFT_Item_SteraksGage: 34
   TFT_Item_Bloodthirster: 33

🎯 Units with Most Items:
   TFT16_Seraphine: 22 times with 3+ items
   TFT16_Taric: 20 times with 3+ items
   TFT16_Wukong: 20 times with 3+ items
   TFT16_Lissandra: 15 times with 3+ items
   TFT16_Shyvana: 15 times with 3+ items
   TFT16_Braum: 14 times with 3+ items
   TFT16_Swain: 14 times with 3+ items
   TFT16_AurelionSol: 13 times with 3+ items
   TFT16_Yunara: 13 times with 3+ items
   TFT16_Warwick: 10 times with 3+ items