# 🏆 TFT Leaderboard Crawler - VN2 Server

In [5]:
!pip -q install requests pandas python-dotenv

In [9]:
pip install "numpy<2.0"

Collecting numpy<2.0
  Downloading numpy-1.26.4-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (61 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.0/61.0 kB 848.6 kB/s eta 0:00:00 0:00:01
Downloading numpy-1.26.4-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (18.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.3/18.3 MB 5.9 MB/s eta 0:00:0000:0100:01
Installing collected packages: numpy
  Attempting uninstall: numpy
    Found existing installation: numpy 2.4.1
    Uninstalling numpy-2.4.1:
      Successfully uninstalled numpy-2.4.1
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
moshi-personaplex 0.1.0 requires huggingface-hub<0.25,>=0.24, but you have huggingface-hub 0.36.0 which is incompatible.
moshi-personaplex 0.1.0 requires sphn<0.2,>=0.1.4, but you have sphn 0.2.1 which is incompatible.
transformers 5.0.0 requires huggingface-hub<2.0,>=1.3.0, but you have huggingface-hub 0.36.0 which is incompatible.
torchvision 0.21.0 requires torch==2.6.0, but you have torch 2.4.1 which is incompatible.
numba 0.57.1 requires numpy<1.25,>=1.21, but you have numpy 1.26.4 which is incompatible.
Successfully installed numpy-1.26.4
Note: you may need to restart the kernel to use updated packages.

In [ ]:
# ========================================
# CELL 1: CONFIG
# ========================================

import os
import requests
import time
import json
import pandas as pd
from datetime import datetime
from dotenv import load_dotenv

# load Riot API Key
load_dotenv()
RIOT_API_KEY = os.getenv("RIOT_API_KEY")

PLATFORM = "vn2"
REGION_ACCOUNT = "asia"
REGION_MATCH = "sea"

TOP_N = 150
MATCH_COUNT_PER_PLAYER = 200

print("✅ Config loaded!")

✅ Config loaded!

In [4]:
# ========================================
# CELL 2: API FUNCTIONS
# ========================================

def make_api_request(url, params=None):
    headers = {"X-Riot-Token": RIOT_API_KEY}
    try:
        response = requests.get(url, headers=headers, params=params)
        if response.status_code == 200:
            return response.json()
        elif response.status_code == 429:
            retry_after = int(response.headers.get('Retry-After', 10))
            print(f"⏳ Rate limited. Waiting {retry_after}s...")
            time.sleep(retry_after)
            return make_api_request(url, params)
        return None
    except Exception as e:
        print(f"❌ Error: {e}")
        return None

def format_timestamp(timestamp_ms):
    return datetime.fromtimestamp(timestamp_ms / 1000).strftime('%Y-%m-%d %H:%M:%S')

def format_unit_info(unit):
    """Format thông tin chi tiết của một unit"""
    name = unit.get('character_id', 'Unknown')
    tier = unit.get('tier', 1)  # Star level (1-3)
    rarity = unit.get('rarity', 0)  # Cost (0=1cost, 1=2cost, etc)
    items = unit.get('itemNames', [])  # Item names
    
    # Rarity to cost mapping
    cost = rarity + 1
    
    # Format items
    items_str = '+'.join(items) if items else 'No items'
    
    return {
        'name': name,
        'tier': tier,
        'cost': cost,
        'items': items_str,
        'item_count': len(items)
    }

print("✅ Functions loaded!")

✅ Functions loaded!

In [5]:
# ========================================
# CELL 3: FETCH LEADERBOARD
# ========================================

print("🏆 Fetching TFT Leaderboard...\n")

all_players = []

url = f"https://{PLATFORM}.api.riotgames.com/tft/league/v1/challenger"
data = make_api_request(url)
if data:
    entries = data.get('entries', [])
    for e in entries:
        e['tier'] = 'CHALLENGER'
        all_players.append(e)
    print(f"✅ Challenger: {len(entries)}")

if len(all_players) < TOP_N:
    url = f"https://{PLATFORM}.api.riotgames.com/tft/league/v1/grandmaster"
    data = make_api_request(url)
    if data:
        entries = data.get('entries', [])
        for e in entries:
            e['tier'] = 'GRANDMASTER'
            all_players.append(e)
        print(f"✅ Grandmaster: {len(entries)}")

all_players = sorted(all_players, key=lambda x: x.get('leaguePoints', 0), reverse=True)
top_players = all_players[:TOP_N]

print(f"\n🏆 Top {len(top_players)} selected!")

🏆 Fetching TFT Leaderboard...

✅ Challenger: 450

🏆 Top 150 selected!

In [6]:
# ========================================
# CELL 4: GET RIOT IDs
# ========================================

print("📋 Fetching Riot IDs...\n")

top_players_detailed = []

for i, player in enumerate(top_players, 1):
    puuid = player.get('puuid')
    print(f"⏳ [{i}/{len(top_players)}] ", end="")
    
    if puuid:
        account_url = f"https://{REGION_ACCOUNT}.api.riotgames.com/riot/account/v1/accounts/by-puuid/{puuid}"
        account_data = make_api_request(account_url)
        
        if account_data:
            game_name = account_data.get('gameName', 'Unknown')
            tag_line = account_data.get('tagLine', 'VN2')
            riot_id = f"{game_name}#{tag_line}"
            
            info = {
                'rank': i,
                'riot_id': riot_id,
                'game_name': game_name,
                'tag_line': tag_line,
                'tier': player.get('tier'),
                'lp': player.get('leaguePoints', 0),
                'wins': player.get('wins', 0),
                'losses': player.get('losses', 0),
                'puuid': puuid
            }
            info['total_games'] = info['wins'] + info['losses']
            info['win_rate'] = round(info['wins'] / info['total_games'] * 100, 1) if info['total_games'] > 0 else 0
            
            top_players_detailed.append(info)
            print(f"✅ {riot_id} ({info['lp']} LP)")
        else:
            print(f"❌ Failed")
    else:
        print(f"❌ No PUUID")
    
    time.sleep(0.3)

print(f"\n✅ Got {len(top_players_detailed)} players!")

📋 Fetching Riot IDs...

⏳ [1/150] ✅ Hoàng Đế Shurima#2911 (2103 LP)
⏳ [2/150] ✅ EA7 longbentre#0910 (1956 LP)
⏳ [3/150] ✅ k3tdc#1st (1898 LP)
⏳ [4/150] ✅ HnZ Luckyboiz#0912 (1859 LP)
⏳ [5/150] ✅ Chunj1#chun (1851 LP)
⏳ [6/150] ✅ TìmLạiChínhMình#0907 (1785 LP)
⏳ [7/150] ✅ YBY1#0615 (1747 LP)
⏳ [8/150] ✅ Kharik#1403 (1720 LP)
⏳ [9/150] ✅ Vô Ám Giả#1982 (1692 LP)
⏳ [10/150] ✅ BBQ FEEDLATAO#2508 (1672 LP)
⏳ [11/150] ✅ VP Lê Chuyên#2311 (1650 LP)
⏳ [12/150] ✅ this game sucks#2501 (1647 LP)
⏳ [13/150] ✅ TrungNguyen#257 (1640 LP)
⏳ [14/150] ✅ VP Maris#Maris (1636 LP)
⏳ [15/150] ✅ GD Royal#1704 (1595 LP)
⏳ [16/150] ✅ Mọc 6 Túi#n6m (1588 LP)
⏳ [17/150] ✅ VP Succulento#poggo (1561 LP)
⏳ [18/150] ✅ Quỷ Vương Đây#6262 (1549 LP)
⏳ [19/150] ✅ changes#DVu (1548 LP)
⏳ [20/150] ✅ Bánh Xíu Páo#2605 (1548 LP)
⏳ [21/150] ✅ HnZ  sơnsmaill#JAV (1548 LP)
⏳ [22/150] ✅ MeoM3o#3636 (1541 LP)
⏳ [23/150] ✅ SSC D2JP#1129 (1531 LP)
⏳ [24/150] ✅ Killua Zoldyc#1999 (1527 LP)
⏳ [25/150] ✅ MG Final#CKTG (1527 LP)
⏳ [26/150] ✅ Kashtira Fenrir#hanss (1524 LP)
⏳ [27/150] ✅ Dean#1711 (1523 LP)
⏳ [28/150] ✅ Stillness1#0910 (1521 LP)
⏳ [29/150] ✅ DR Chase#0612 (1517 LP)
⏳ [30/150] ✅ KNG Cchh#1005 (1516 LP)
⏳ [31/150] ✅ Quang TX#1997 (1515 LP)
⏳ [32/150] ✅ HND TFT#1702 (1505 LP)
⏳ [33/150] ✅ nothing to lose#lth (1504 LP)
⏳ [34/150] ✅ DeeA#0801 (1501 LP)
⏳ [35/150] ✅ nguyenvux#vux (1497 LP)
⏳ [36/150] ✅ Sb Yunabi#Upppp (1489 LP)
⏳ [37/150] ✅ baenicaa#0311 (1487 LP)
⏳ [38/150] ✅ iCeEmperoz#mind (1486 LP)
⏳ [39/150] ✅ A Tẩm#1610 (1475 LP)
⏳ [40/150] ✅ Ước gì bớt đẳng#010 (1468 LP)
⏳ [41/150] ✅ MF xiaoyi#6868 (1460 LP)
⏳ [42/150] ✅ RRQ Asta#0497 (1452 LP)
⏳ [43/150] ✅ Sb flaw#ptqa (1450 LP)
⏳ [44/150] ✅ KND Last Dance#Lugh1 (1447 LP)
⏳ [45/150] ✅ HUST thôi#vn2 (1447 LP)
⏳ [46/150] ✅ Minorita#ducpl (1441 LP)
⏳ [47/150] ✅ JayDee#1509 (1440 LP)
⏳ [48/150] ✅ Gián Chết Trôi#172 (1436 LP)
⏳ [49/150] ✅ Marcus1#1107 (1429 LP)
⏳ [50/150] ✅ SW Llaih#Hiast (1426 LP)
⏳ [51/150] ✅ BéngThihi#0801 (1424 LP)
⏳ [52/150] ✅ Chunj2#chun (1420 LP)
⏳ [53/150] ✅ BọSiêuRì#simp (1419 LP)
⏳ [54/150] ✅ TOP1 CKTG#7777 (1415 LP)
⏳ [55/150] ✅ chihuyconga#rumeo (1414 LP)
⏳ [56/150] ✅ Trúc Cơ Sơ Kỳ#han1 (1414 LP)
⏳ [57/150] ✅ GD Khar1ch#611 (1411 LP)
⏳ [58/150] ✅ Arizona K#2607 (1401 LP)
⏳ [59/150] ✅ Em Dứa#2310 (1396 LP)
⏳ [60/150] ✅ dohaianh1996bn#0104 (1395 LP)
⏳ [61/150] ✅ Neekotine#minh (1393 LP)
⏳ [62/150] ✅ wowlon#4444 (1390 LP)
⏳ [63/150] ✅ Alex Đi CKTG#1611 (1389 LP)
⏳ [64/150] ✅ KAQ Destiny#Desti (1389 LP)
⏳ [65/150] ✅ KOS No1 Lobby#BB1 (1382 LP)
⏳ [66/150] ✅ Em Chè đi CKTG#3007 (1377 LP)
⏳ [67/150] ✅ ynwxx#2105 (1368 LP)
⏳ [68/150] ✅ LifeSquare#2265 (1363 LP)
⏳ [69/150] ✅ Vic1#1309 (1361 LP)
⏳ [70/150] ✅ oOoBlackRose#vn2 (1359 LP)
⏳ [71/150] ✅ MF Mèo Hor1#colen (1359 LP)
⏳ [72/150] ✅ KissKiss#imV (1358 LP)
⏳ [73/150] ✅ Mendes#0803 (1353 LP)
⏳ [74/150] ✅ Shader1#ea7 (1351 LP)
⏳ [75/150] ✅ m1se#1506 (1351 LP)
⏳ [76/150] ✅ RRQ pk1#2311 (1349 LP)
⏳ [77/150] ✅ BN vtt#VTT (1339 LP)
⏳ [78/150] ✅ Song Tỵ#1803 (1338 LP)
⏳ [79/150] ✅ 7 úp#12596 (1333 LP)
⏳ [80/150] ✅ hoangthanh1996ht#2508 (1331 LP)
⏳ [81/150] ✅ Tho hac tinh#2204 (1328 LP)
⏳ [82/150] ✅ VP k1an#phanh (1327 LP)
⏳ [83/150] ✅ NTVA#0805 (1317 LP)
⏳ [84/150] ✅ ynwxxx2#2105 (1312 LP)
⏳ [85/150] ✅ Bình Chữa Cháy#2204 (1311 LP)
⏳ [86/150] ✅ Sb VietHa#0711 (1309 LP)
⏳ [87/150] ✅ Đầu Trâu Mặt Hổ#113 (1308 LP)
⏳ [88/150] ✅ ironsoap#2510 (1307 LP)
⏳ [89/150] ✅ Noizi#sad (1306 LP)
⏳ [90/150] ✅ lil crazy1ove#emtit (1303 LP)
⏳ [91/150] ✅ SW yuipp#0522 (1301 LP)
⏳ [92/150] ✅ EA7 K1dz#7le (1298 LP)
⏳ [93/150] ✅ Dasno#thp (1290 LP)
⏳ [94/150] ✅ Dizzyland#zzz (1290 LP)
⏳ [95/150] ✅ 2xchipchip#2208 (1288 LP)
⏳ [96/150] ✅ Ghiền Ixtal#ghien (1288 LP)
⏳ [97/150] ✅ VP NCC1#3101 (1287 LP)
⏳ [98/150] ✅ Alive1#Riri1 (1285 LP)
⏳ [99/150] ✅ papago#Mzcb (1284 LP)
⏳ [100/150] ✅ puppy2fast#1521 (1284 LP)
⏳ [101/150] ⏳ Rate limited. Waiting 53s...
✅ Vì Tinh Tú#dom (1281 LP)
⏳ [102/150] ✅ KOS JeyT1#888 (1281 LP)
⏳ [103/150] ✅ KhuêHP#3011 (1280 LP)
⏳ [104/150] ✅ top1spammer12#vn2 (1278 LP)
⏳ [105/150] ✅ Genos1#PTA (1275 LP)
⏳ [106/150] ✅ DPF Hisu#2107 (1274 LP)
⏳ [107/150] ✅ MP Welwel#2904 (1273 LP)
⏳ [108/150] ✅ Zero King1#PV111 (1272 LP)
⏳ [109/150] ✅ WoaWoaWoa#2424 (1270 LP)
⏳ [110/150] ✅ FUW Hyu#218 (1270 LP)
⏳ [111/150] ✅ MF JoyBoy#TAV (1270 LP)
⏳ [112/150] ✅ 4 game 36 điểm#mdmd (1268 LP)
⏳ [113/150] ✅ LOVEMUFFIN#818 (1267 LP)
⏳ [114/150] ✅ Nghé Cục Cưng#1207 (1266 LP)
⏳ [115/150] ✅ WANO OLY#0512 (1258 LP)
⏳ [116/150] ✅ VaDerA#vn2 (1257 LP)
⏳ [117/150] ✅ iCTSV#2702 (1255 LP)
⏳ [118/150] ✅ baby im back#Định (1250 LP)
⏳ [119/150] ✅ JP 4ttention#2000 (1250 LP)
⏳ [120/150] ✅ Hải An mất em#3009 (1250 LP)
⏳ [121/150] ✅ Hàn Lập#hzzzz (1245 LP)
⏳ [122/150] ✅ Tớ chọn cậu#1205 (1244 LP)
⏳ [123/150] ✅ hongduc1#2401 (1242 LP)
⏳ [124/150] ✅ MF Lemonss#0810 (1241 LP)
⏳ [125/150] ✅ EA7 Gnut#2004 (1239 LP)
⏳ [126/150] ✅ Chill chiu#chill (1237 LP)
⏳ [127/150] ✅ sự tĩnh lặng#1993 (1236 LP)
⏳ [128/150] ✅ 4Nine Fieren#Banh (1234 LP)
⏳ [129/150] ✅ từ con số 0#1407 (1234 LP)
⏳ [130/150] ✅ NNG Blade#148 (1234 LP)
⏳ [131/150] ✅ DamzVN#2969 (1234 LP)
⏳ [132/150] ✅ Emperor 大国王#1111 (1233 LP)
⏳ [133/150] ✅ tftiseasy#00000 (1232 LP)
⏳ [134/150] ✅ RNG Souma#189 (1230 LP)
⏳ [135/150] ✅ CP Romeo#Roeee (1226 LP)
⏳ [136/150] ✅ Dante#LTD (1225 LP)
⏳ [137/150] ✅ Hắc Vũ#19x (1224 LP)
⏳ [138/150] ✅ NguyenDuyHoanh#2001 (1220 LP)
⏳ [139/150] ✅ Tom Cat#meo (1217 LP)
⏳ [140/150] ✅ IronBug1#153 (1216 LP)
⏳ [141/150] ✅ VP Milo#EA7 (1213 LP)
⏳ [142/150] ✅ Alizabé Lan#2703 (1211 LP)
⏳ [143/150] ✅ MăngCụtTFT#Live (1209 LP)
⏳ [144/150] ✅ Hoang#0110 (1206 LP)
⏳ [145/150] ✅ NướcĐáiTinhKhiết#NDTK (1205 LP)
⏳ [146/150] ✅ vinsontheween#210 (1203 LP)
⏳ [147/150] ✅ MP thinhh1#1208 (1203 LP)
⏳ [148/150] ✅ Coriander#coang (1202 LP)
⏳ [149/150] ✅ sansaniuu#2301 (1201 LP)
⏳ [150/150] ✅ Capybara#4266 (1199 LP)

✅ Got 150 players!

In [7]:
# ========================================
# CELL 5: DISPLAY LEADERBOARD
# ========================================

leaderboard_df = pd.DataFrame(top_players_detailed)

if len(leaderboard_df) > 0:
    print(f"\n🏆 TFT LEADERBOARD - VN2 - TOP {len(leaderboard_df)}\n")
    pd.set_option('display.max_rows', 50)
    display(leaderboard_df[['rank', 'riot_id', 'tier', 'lp', 'wins', 'losses', 'win_rate', 'total_games']])

🏆 TFT LEADERBOARD - VN2 - TOP 150

,rank,riot_id,tier,lp,wins,losses,win_rate,total_games
0,1,Hoàng Đế Shurima#2911,CHALLENGER,2103,249,100,71.3,349
1,2,EA7 longbentre#0910,CHALLENGER,1956,590,339,63.5,929
2,3,k3tdc#1st,CHALLENGER,1898,271,154,63.8,425
3,4,HnZ Luckyboiz#0912,CHALLENGER,1859,388,195,66.6,583
4,5,Chunj1#chun,CHALLENGER,1851,445,272,62.1,717
...,...,...,...,...,...,...,...,...
145,146,vinsontheween#210,CHALLENGER,1203,278,212,56.7,490
146,147,MP thinhh1#1208,CHALLENGER,1203,239,203,54.1,442
147,148,Coriander#coang,CHALLENGER,1202,306,247,55.3,553
148,149,sansaniuu#2301,CHALLENGER,1201,296,226,56.7,522
149,150,Capybara#4266,CHALLENGER,1199,217,155,58.3,372

In [ ]:
# ========================================
# CELL 6: FETCH MATCH HISTORY (với unit details)
# ========================================

if len(top_players_detailed) == 0:
    print("⚠️ No players to fetch.")
else:
    print(f"📊 Fetching match history ({MATCH_COUNT_PER_PLAYER} matches/player)...\n")
    
    all_player_stats = []  # Match stats
    all_unit_details = []  # Unit details per match
    
    for player in top_players_detailed:
        puuid = player['puuid']
        riot_id = player['riot_id']
        rank = player['rank']
        
        print(f"🎮 [{rank}] {riot_id} ", end="")
        
        match_url = f"https://{REGION_MATCH}.api.riotgames.com/tft/match/v1/matches/by-puuid/{puuid}/ids"
        match_ids = make_api_request(match_url, {"count": MATCH_COUNT_PER_PLAYER})
        
        if not match_ids:
            print("⚠️ No matches")
            continue
        
        matches_fetched = 0
        for match_id in match_ids:
            detail_url = f"https://{REGION_MATCH}.api.riotgames.com/tft/match/v1/matches/{match_id}"
            match_detail = make_api_request(detail_url)
            
            if match_detail:
                info = match_detail.get('info', {})
                for p in info.get('participants', []):
                    if p.get('puuid') == puuid:
                        # Traits
                        traits = [t['name'] for t in p.get('traits', []) if t.get('tier_current', 0) > 0]
                        
                        # Units với chi tiết
                        units = p.get('units', [])
                        unit_names = []
                        unit_details_str = []
                        
                        for unit in units:
                            unit_info = format_unit_info(unit)
                            unit_names.append(unit_info['name'])
                            
                            # Format: Name(tier★, cost$, items)
                            detail = f"{unit_info['name']}({unit_info['tier']}★{unit_info['cost']}$)"
                            if unit_info['item_count'] > 0:
                                detail += f"[{unit_info['items']}]"
                            unit_details_str.append(detail)
                            
                            # Lưu chi tiết riêng cho phân tích
                            all_unit_details.append({
                                'riot_id': riot_id,
                                'match_id': match_id,
                                'placement': p.get('placement'),
                                'unit_name': unit_info['name'],
                                'unit_tier': unit_info['tier'],
                                'unit_cost': unit_info['cost'],
                                'unit_items': unit_info['items'],
                                'item_count': unit_info['item_count']
                            })
                        
                        # Match stats
                        all_player_stats.append({
                            'riot_id': riot_id,
                            'leaderboard_rank': rank,
                            'match_id': match_id,
                            'datetime': format_timestamp(info.get('game_datetime', 0)),
                            'placement': p.get('placement'),
                            'level': p.get('level'),
                            'traits': ', '.join(traits[:5]),
                            'units': ', '.join(unit_names),
                            'units_detailed': ' | '.join(unit_details_str),
                            'num_units': len(units)
                        })
                        matches_fetched += 1
                        break
            time.sleep(0.25)
        
        print(f"✅ {matches_fetched} matches")
    
    print(f"\n✅ Total: {len(all_player_stats)} matches, {len(all_unit_details)} unit records")

📊 Fetching match history (200 matches/player)...

🎮 [1] Hoàng Đế Shurima#2911 ⏳ Rate limited. Waiting 12s...
⏳ Rate limited. Waiting 69s...
❌ Error: HTTPSConnectionPool(host='sea.api.riotgames.com', port=443): Max retries exceeded with url: /tft/match/v1/matches/VN2_1207560265 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7a5faedad350>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
❌ Error: HTTPSConnectionPool(host='sea.api.riotgames.com', port=443): Max retries exceeded with url: /tft/match/v1/matches/VN2_1198151532 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7a601c17d490>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
⏳ Rate limited. Waiting 57s...
❌ Error: HTTPSConnectionPool(host='sea.api.riotgames.com', port=443): Max retries exceeded with url: /tft/match/v1/matches/VN2_1187076518 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7a5faed2c410>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
❌ Error: HTTPSConnectionPool(host='sea.api.riotgames.com', port=443): Max retries exceeded with url: /tft/match/v1/matches/VN2_1183670784 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7a5faedd1fd0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
⏳ Rate limited. Waiting 54s...
❌ Error: HTTPSConnectionPool(host='sea.api.riotgames.com', port=443): Max retries exceeded with url: /tft/match/v1/matches/VN2_1180096908 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7a5faeec51d0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
✅ 195 matches
🎮 [2] EA7 longbentre#0910 ⏳ Rate limited. Waiting 56s...
⏳ Rate limited. Waiting 69s...
⏳ Rate limited. Waiting 67s...
⏳ Rate limited. Waiting 65s...
✅ 200 matches
🎮 [3] k3tdc#1st ⏳ Rate limited. Waiting 56s...
❌ Error: HTTPSConnectionPool(host='sea.api.riotgames.com', port=443): Max retries exceeded with url: /tft/match/v1/matches/VN2_1198541120 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7a5faeb42c90>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
❌ Error: HTTPSConnectionPool(host='sea.api.riotgames.com', port=443): Max retries exceeded with url: /tft/match/v1/matches/VN2_1196855480 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7a5faeb6b3d0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
⏳ Rate limited. Waiting 62s...
⏳ Rate limited. Waiting 68s...
❌ Error: HTTPSConnectionPool(host='sea.api.riotgames.com', port=443): Max retries exceeded with url: /tft/match/v1/matches/VN2_1178690411 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7a5fae9f1a90>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
✅ 197 matches
🎮 [4] HnZ Luckyboiz#0912 ⏳ Rate limited. Waiting 60s...
⏳ Rate limited. Waiting 69s...
⏳ Rate limited. Waiting 69s...
✅ 200 matches
🎮 [5] Chunj1#chun ⏳ Rate limited. Waiting 65s...
⏳ Rate limited. Waiting 67s...
⏳ Rate limited. Waiting 66s...
❌ Error: HTTPSConnectionPool(host='sea.api.riotgames.com', port=443): Max retries exceeded with url: /tft/match/v1/matches/VN2_1202835744 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7a5fae949a90>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
✅ 199 matches
🎮 [6] TìmLạiChínhMình#0907 ⏳ Rate limited. Waiting 60s...
⏳ Rate limited. Waiting 59s...
❌ Error: HTTPSConnectionPool(host='sea.api.riotgames.com', port=443): Max retries exceeded with url: /tft/match/v1/matches/VN2_1222012290 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7a5fae813450>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
❌ Error: HTTPSConnectionPool(host='sea.api.riotgames.com', port=443): Max retries exceeded with url: /tft/match/v1/matches/VN2_1212751097 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7a5fae839490>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
⏳ Rate limited. Waiting 62s...
⏳ Rate limited. Waiting 55s...
✅ 198 matches
🎮 [7] YBY1#0615 ⏳ Rate limited. Waiting 67s...
⏳ Rate limited. Waiting 64s...
⏳ Rate limited. Waiting 67s...
✅ 200 matches
🎮 [8] Kharik#1403 ⏳ Rate limited. Waiting 64s...
⏳ Rate limited. Waiting 60s...
⏳ Rate limited. Waiting 52s...
⏳ Rate limited. Waiting 56s...
✅ 200 matches
🎮 [9] Vô Ám Giả#1982 ⏳ Rate limited. Waiting 60s...
⏳ Rate limited. Waiting 67s...
⏳ Rate limited. Waiting 70s...
✅ 200 matches
🎮 [10] BBQ FEEDLATAO#2508 ⏳ Rate limited. Waiting 61s...
⏳ Rate limited. Waiting 67s...
⏳ Rate limited. Waiting 67s...
✅ 200 matches
🎮 [11] VP Lê Chuyên#2311 ⏳ Rate limited. Waiting 70s...
⏳ Rate limited. Waiting 72s...
⏳ Rate limited. Waiting 66s...
✅ 200 matches
🎮 [12] this game sucks#2501 ⏳ Rate limited. Waiting 71s...
⏳ Rate limited. Waiting 70s...
❌ Error: HTTPSConnectionPool(host='sea.api.riotgames.com', port=443): Max retries exceeded with url: /tft/match/v1/matches/VN2_1205057260 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7a5fae366610>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
⏳ Rate limited. Waiting 68s...
✅ 199 matches
🎮 [13] TrungNguyen#257 ⏳ Rate limited. Waiting 69s...

In [12]:
# ========================================
# CELL 7: DISPLAY & SAVE DATA
# ========================================

match_df = pd.DataFrame(all_player_stats) if 'all_player_stats' in dir() and all_player_stats else pd.DataFrame()
unit_df = pd.DataFrame(all_unit_details) if 'all_unit_details' in dir() and all_unit_details else pd.DataFrame()

print("💾 Saving...\n")

# Save leaderboard
if len(leaderboard_df) > 0:
    filename = f"tft_leaderboard_{PLATFORM}_top{TOP_N}.csv"
    leaderboard_df.to_csv(filename, index=False, encoding='utf-8-sig')
    print(f"✅ {filename}")

# Save match history
if len(match_df) > 0:
    filename = f"tft_matches_{PLATFORM}_top{TOP_N}.csv"
    match_df.to_csv(filename, index=False, encoding='utf-8-sig')
    print(f"✅ {filename}")

# Save unit details
if len(unit_df) > 0:
    filename = f"tft_units_{PLATFORM}_top{TOP_N}.csv"
    unit_df.to_csv(filename, index=False, encoding='utf-8-sig')
    print(f"✅ {filename}")

print("\n📊 Match History Preview:")
if len(match_df) > 0:
    display(match_df[['riot_id', 'placement', 'level', 'units_detailed']].head(10))

print("\n📊 Unit Details Preview:")
if len(unit_df) > 0:
    display(unit_df.head(20))

print("\n🎉 Done!")

💾 Saving...

✅ tft_leaderboard_vn2_top150.csv
✅ tft_matches_vn2_top150.csv
✅ tft_units_vn2_top150.csv

📊 Match History Preview:

,riot_id,placement,level,units_detailed
0,Hoàng Đế Shurima#2911,4,9,TFT16_KogMaw(2★1$) | TFT16_ChoGath(2★2$) | TFT...
1,Hoàng Đế Shurima#2911,1,8,TFT16_Vi(2★2$) | TFT16_Orianna(2★2$)[TFT_Item_...
2,Hoàng Đế Shurima#2911,1,10,TFT16_KogMaw(2★1$) | TFT16_Sion(2★2$) | TFT16_...
3,Hoàng Đế Shurima#2911,7,8,TFT16_Shen(2★1$) | TFT16_Ashe(1★2$) | TFT16_Ah...
4,Hoàng Đế Shurima#2911,1,10,TFT16_Vi(2★2$) | TFT16_Orianna(2★2$) | TFT16_S...
5,Hoàng Đế Shurima#2911,1,9,TFT16_Caitlyn(1★1$) | TFT16_Loris(1★3$) | TFT1...
6,Hoàng Đế Shurima#2911,3,9,TFT16_Neeko(2★2$) | TFT16_Vi(2★2$) | TFT16_Jin...
7,Hoàng Đế Shurima#2911,1,8,TFT16_Illaoi(2★1$) | TFT16_Sion(2★2$) | TFT16_...
8,Hoàng Đế Shurima#2911,1,10,TFT16_Illaoi(1★1$) | TFT16_TwistedFate(2★2$)[T...
9,Hoàng Đế Shurima#2911,6,8,TFT16_JarvanIV(2★1$) | TFT16_XinZhao(2★2$) | T...

📊 Unit Details Preview:

,riot_id,match_id,placement,unit_name,unit_tier,unit_cost,unit_items,item_count
0,Hoàng Đế Shurima#2911,VN2_1240385846,4,TFT16_KogMaw,2,1,No items,0
1,Hoàng Đế Shurima#2911,VN2_1240385846,4,TFT16_ChoGath,2,2,No items,0
2,Hoàng Đế Shurima#2911,VN2_1240385846,4,TFT16_Malzahar,2,3,TFT16_Item_InvokerEmblemItem+TFT_Item_RapidFir...,3
3,Hoàng Đế Shurima#2911,VN2_1240385846,4,TFT16_Kobuko,2,3,TFT_Item_Redemption+TFT_Item_SparringGloves,2
4,Hoàng Đế Shurima#2911,VN2_1240385846,4,TFT16_RiftHerald,2,5,TFT_Item_WarmogsArmor+TFT_Item_SpectralGauntle...,3
5,Hoàng Đế Shurima#2911,VN2_1240385846,4,TFT16_Kaisa,2,5,TFT_Item_SpearOfShojin+TFT_Item_PowerGauntlet+...,3
6,Hoàng Đế Shurima#2911,VN2_1240385846,4,TFT16_Renekton,2,5,TFT16_Item_VoidEmblemItem+TFT16_Item_YordleEmb...,3
7,Hoàng Đế Shurima#2911,VN2_1240385846,4,TFT16_Azir,1,7,No items,0
8,Hoàng Đế Shurima#2911,VN2_1240385846,4,TFT16_Shyvana,2,7,TFT_Item_ThiefsGloves+TFT_Item_RedBuff+TFT_Ite...,3
9,Hoàng Đế Shurima#2911,VN2_1240373128,1,TFT16_Vi,2,2,No items,0
10,Hoàng Đế Shurima#2911,VN2_1240373128,1,TFT16_Orianna,2,2,TFT_Item_RecurveBow,1
11,Hoàng Đế Shurima#2911,VN2_1240373128,1,TFT16_Sejuani,2,3,TFT_Item_DragonsClaw+TFT_Item_FrozenHeart+TFT_...,3
12,Hoàng Đế Shurima#2911,VN2_1240373128,1,TFT16_Loris,2,3,TFT_Item_ThiefsGloves+TFT_Item_RunaansHurrican...,3
13,Hoàng Đế Shurima#2911,VN2_1240373128,1,TFT16_Lissandra,2,5,TFT_Item_UnstableConcoction+TFT_Item_StatikkSh...,3
14,Hoàng Đế Shurima#2911,VN2_1240373128,1,TFT16_Seraphine,3,5,TFT_Item_RabadonsDeathcap+TFT_Item_HextechGunb...,3
15,Hoàng Đế Shurima#2911,VN2_1240373128,1,TFT16_Braum,3,5,TFT_Item_FrozenHeart+TFT_Item_UnstableConcocti...,3
16,Hoàng Đế Shurima#2911,VN2_1240373128,1,TFT16_Azir,1,7,No items,0
17,Hoàng Đế Shurima#2911,VN2_1240360102,1,TFT16_KogMaw,2,1,No items,0
18,Hoàng Đế Shurima#2911,VN2_1240360102,1,TFT16_Sion,2,2,No items,0
19,Hoàng Đế Shurima#2911,VN2_1240360102,1,TFT16_Ambessa,2,5,TFT16_Item_VoidEmblemItem+TFT_Item_SparringGloves,2

🎉 Done!

In [13]:
# ========================================
# CELL 8: ANALYZE UNITS
# ========================================

if len(unit_df) > 0:
    print("📊 UNIT ANALYSIS\n")
    
    # Most used units
    print("🔥 Most Used Units:")
    unit_counts = unit_df['unit_name'].value_counts().head(15)
    for unit, count in unit_counts.items():
        print(f"   {unit}: {count}")
    
    # Most common 3-star units
    print("\n⭐ Most Common 3-Star Units:")
    three_star = unit_df[unit_df['unit_tier'] == 3]['unit_name'].value_counts().head(10)
    for unit, count in three_star.items():
        print(f"   {unit}: {count}")
    
    # Most common items
    print("\n🛡️ Most Common Items:")
    all_items = []
    for items_str in unit_df['unit_items'].dropna():
        if items_str and items_str != 'No items':
            items = items_str.split('+')
            all_items.extend(items)
    
    item_counts = pd.Series(all_items).value_counts().head(15)
    for item, count in item_counts.items():
        print(f"   {item}: {count}")
    
    # Units with most items
    print("\n🎯 Units with Most Items:")
    carry_units = unit_df[unit_df['item_count'] >= 3].groupby('unit_name').size().sort_values(ascending=False).head(10)
    for unit, count in carry_units.items():
        print(f"   {unit}: {count} times with 3+ items")

📊 UNIT ANALYSIS

🔥 Most Used Units:
   TFT16_Swain: 14782
   TFT16_Taric: 11592
   TFT16_Shyvana: 10080
   TFT16_Vi: 8934
   TFT16_Wukong: 8449
   TFT16_Lucian: 8392
   TFT16_Seraphine: 7657
   TFT16_Fiddlesticks: 6154
   TFT16_Neeko: 5877
   TFT16_Kindred: 5641
   TFT16_Azir: 5344
   TFT16_Sett: 5149
   TFT16_Braum: 4902
   TFT16_Volibear: 4745
   TFT16_Lissandra: 4292

⭐ Most Common 3-Star Units:
   TFT16_Neeko: 1442
   TFT16_Ekko: 989
   TFT16_Vi: 885
   TFT16_JarvanIV: 814
   TFT16_TwistedFate: 778
   TFT16_Caitlyn: 706
   TFT16_Sona: 648
   TFT16_Bard: 637
   TFT16_Gangplank: 601
   TFT16_Graves: 496

🛡️ Most Common Items:
   TFT_Item_GuinsoosRageblade: 17040
   TFT_Item_ThiefsGloves: 16568
   TFT_Item_JeweledGauntlet: 15356
   TFT_Item_Redemption: 13544
   TFT_Item_InfinityEdge: 13036
   TFT_Item_GargoyleStoneplate: 13017
   TFT_Item_WarmogsArmor: 12801
   TFT_Item_SpearOfShojin: 12559
   TFT_Item_Bloodthirster: 12054
   TFT_Item_RedBuff: 11823
   TFT_Item_StatikkShiv: 10708
   TFT_Item_FrozenHeart: 10453
   TFT_Item_Morellonomicon: 10186
   TFT_Item_AdaptiveHelm: 9593
   TFT_Item_MadredsBloodrazor: 8989

🎯 Units with Most Items:
   TFT16_Wukong: 4648 times with 3+ items
   TFT16_Swain: 4053 times with 3+ items
   TFT16_Taric: 3877 times with 3+ items
   TFT16_Shyvana: 3586 times with 3+ items
   TFT16_Seraphine: 3500 times with 3+ items
   TFT16_Sett: 3481 times with 3+ items
   TFT16_Lucian: 3326 times with 3+ items
   TFT16_Ziggs: 3110 times with 3+ items
   TFT16_Yunara: 2945 times with 3+ items
   TFT16_Volibear: 2941 times with 3+ items